#!/bin/sh

chmod u+x ./mypipoxman

if [ -e 'mypipox' ]
then
 rm ./mypipox
 rm ./mypipox.py
else
 wget http://faraway6834.github.io/mypipox.py
 echo "#!/bin/sh\npython mypipox.py" > "mypipox"
 chmod u+x ./mypipox.py
 chmod u+x ./mypipox
fi
