#!/bin/sh
#https://faraway6834.github.io/venvn

chmod u+x "./${0}"

if [ "$1" = "--install" ] ; then
	filename="run${2}"
	
	python -m venv "$2"
	
	echo "#!/bin/sh" > "${filename}"
	echo ". ${2}/bin/activate" >> "${filename}"
	echo "alias exitvenv=\"deactivate\"" >> "${filename}"
	chmod u+x "${filename}"
	
elif [ "$1" = "--uninstall" ] ; then
	filename="run${2}"
	
	rm -rf "${2}"
	rm -f "${filename}"
else
	echo "do --install or --uninstall"
fi